"""Update school management and ugel to enums

Revision ID: 0436dd1be87a
Revises: 92af4a3cd45a
Create Date: 2026-05-01 14:52:00.435707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0436dd1be87a'
down_revision: Union[str, Sequence[str], None] = '92af4a3cd45a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('school', 'management',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PRIVADA', 'PUBLICA', name='managementtype'),
               existing_comment='Name of the management or administrative unit',
               existing_nullable=False)
    op.alter_column('school', 'ugel',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SATIPO', 'RIO_NEGRO', 'MAZAMARI', 'PANGOA', 'PICHANAKI', 'RIO_TAMBO', 'LA_MERCED', 'CONCEPCION', 'JAUJA', 'HUANCAYO', 'OTRO', name='ugel'),
               existing_comment='Local Education Management Unit (UGEL)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('school', 'ugel',
               existing_type=sa.Enum('SATIPO', 'RIO_NEGRO', 'MAZAMARI', 'PANGOA', 'PICHANAKI', 'RIO_TAMBO', 'LA_MERCED', 'CONCEPCION', 'JAUJA', 'HUANCAYO', 'OTRO', name='ugel'),
               type_=sa.VARCHAR(length=50),
               existing_comment='Local Education Management Unit (UGEL)',
               existing_nullable=True)
    op.alter_column('school', 'management',
               existing_type=sa.Enum('PRIVADA', 'PUBLICA', name='managementtype'),
               type_=sa.VARCHAR(length=50),
               existing_comment='Name of the management or administrative unit',
               existing_nullable=False)
    # ### end Alembic commands ###
