"""align string column lengths with schema constraints

Revision ID: 107b7e531283
Revises: 0436dd1be87a
Create Date: 2026-05-01 19:32:55.788647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '107b7e531283'
down_revision: Union[str, Sequence[str], None] = '0436dd1be87a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'dni',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=8),
               existing_comment='National ID document (DNI)',
               existing_nullable=False)
    op.alter_column('employee', 'ruc',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=11),
               existing_comment='Tax identification number (optional)',
               existing_nullable=True)
    op.alter_column('employee', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=9),
               existing_comment='Contact phone number',
               existing_nullable=False)
    op.alter_column('grade', 'name',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=15),
               existing_comment='Name of the academic grade',
               existing_nullable=False)
    op.alter_column('level', 'name',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=15),
               existing_comment='Name of the educational level',
               existing_nullable=False)
    op.alter_column('school', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=9),
               existing_comment='Institutional contact phone number',
               existing_nullable=False)
    op.alter_column('section', 'name',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=15),
               existing_comment='Name of the section',
               existing_nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=15),
               existing_comment='Username of the user',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=25),
               existing_comment='Username of the user',
               existing_nullable=False)
    op.alter_column('section', 'name',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=25),
               existing_comment='Name of the section',
               existing_nullable=False)
    op.alter_column('school', 'phone_number',
               existing_type=sa.String(length=9),
               type_=sa.VARCHAR(length=15),
               existing_comment='Institutional contact phone number',
               existing_nullable=False)
    op.alter_column('level', 'name',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=25),
               existing_comment='Name of the educational level',
               existing_nullable=False)
    op.alter_column('grade', 'name',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=25),
               existing_comment='Name of the academic grade',
               existing_nullable=False)
    op.alter_column('employee', 'phone_number',
               existing_type=sa.String(length=9),
               type_=sa.VARCHAR(length=15),
               existing_comment='Contact phone number',
               existing_nullable=False)
    op.alter_column('employee', 'ruc',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=15),
               existing_comment='Tax identification number (optional)',
               existing_nullable=True)
    op.alter_column('employee', 'dni',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=15),
               existing_comment='National ID document (DNI)',
               existing_nullable=False)
    # ### end Alembic commands ###
