"""Add receipts and employee payments models

Revision ID: 25a10ff7cb39
Revises: c26af8a65e89
Create Date: 2026-04-20 19:14:56.721847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25a10ff7cb39'
down_revision: Union[str, Sequence[str], None] = 'c26af8a65e89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Payment ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Name or title of the payment'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Amount paid'),
    sa.Column('date', sa.Date(), nullable=False, comment='Date of the payment'),
    sa.Column('detail', sa.String(length=100), nullable=True, comment='Optional detail about payment'),
    sa.Column('user_id', sa.SmallInteger(), nullable=False, comment='User ID who recorded the payment'),
    sa.Column('employee_id', sa.SmallInteger(), nullable=False, comment='Employee ID receiving the payment'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_employee_employee_id'), 'payment_employee', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payment_employee_id'), 'payment_employee', ['id'], unique=False)
    op.create_index(op.f('ix_payment_employee_user_id'), 'payment_employee', ['user_id'], unique=False)
    op.create_table('receipt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Receipt ID'),
    sa.Column('date', sa.Date(), nullable=False, comment='Date of the receipt'),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Total receipt amount'),
    sa.Column('guardian_id', sa.Integer(), nullable=False, comment='Guardian ID mapping the person paying'),
    sa.Column('receipt_type', sa.Enum('BOLETA', 'FACTURA', 'OTRO', name='receipttype'), nullable=False, comment='Type of receipt (Boleta, Factura, Otro)'),
    sa.Column('user_id', sa.SmallInteger(), nullable=False, comment='User ID who emitted the receipt'),
    sa.Column('payment_method', sa.Enum('EFECTIVO', 'TARJETA', 'TRANSFERENCIA', 'OTRO', name='paymentmethod'), nullable=False, comment='Method of payment'),
    sa.Column('receipt_file_path', sa.String(length=255), nullable=True, comment='Path to the digital receipt file'),
    sa.Column('payment_evidence_path', sa.String(length=255), nullable=True, comment='Path to the evidence of payment file'),
    sa.Column('detail', sa.String(length=100), nullable=True, comment='Optional detail/description'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardian.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_guardian_id'), 'receipt', ['guardian_id'], unique=False)
    op.create_index(op.f('ix_receipt_id'), 'receipt', ['id'], unique=False)
    op.create_index(op.f('ix_receipt_user_id'), 'receipt', ['user_id'], unique=False)
    op.create_table('receipt_line',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Receipt Line ID'),
    sa.Column('charge_id', sa.Integer(), nullable=False, comment='Charge ID associated'),
    sa.Column('receipt_id', sa.Integer(), nullable=True, comment='Receipt ID associated'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Amount applied to this line'),
    sa.ForeignKeyConstraint(['charge_id'], ['charge.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipt.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_line_charge_id'), 'receipt_line', ['charge_id'], unique=False)
    op.create_index(op.f('ix_receipt_line_id'), 'receipt_line', ['id'], unique=False)
    op.create_index(op.f('ix_receipt_line_receipt_id'), 'receipt_line', ['receipt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipt_line_receipt_id'), table_name='receipt_line')
    op.drop_index(op.f('ix_receipt_line_id'), table_name='receipt_line')
    op.drop_index(op.f('ix_receipt_line_charge_id'), table_name='receipt_line')
    op.drop_table('receipt_line')
    op.drop_index(op.f('ix_receipt_user_id'), table_name='receipt')
    op.drop_index(op.f('ix_receipt_id'), table_name='receipt')
    op.drop_index(op.f('ix_receipt_guardian_id'), table_name='receipt')
    op.drop_table('receipt')
    op.drop_index(op.f('ix_payment_employee_user_id'), table_name='payment_employee')
    op.drop_index(op.f('ix_payment_employee_id'), table_name='payment_employee')
    op.drop_index(op.f('ix_payment_employee_employee_id'), table_name='payment_employee')
    op.drop_table('payment_employee')
    # ### end Alembic commands ###
