"""remove unique from grade name

Revision ID: 4bdccf3f2a17
Revises: a27d1f90b86a
Create Date: 2026-04-23 16:37:28.318025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bdccf3f2a17'
down_revision: Union[str, Sequence[str], None] = 'a27d1f90b86a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grade_name'), table_name='grade')
    op.create_index(op.f('ix_grade_name'), 'grade', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grade_name'), table_name='grade')
    op.create_index(op.f('ix_grade_name'), 'grade', ['name'], unique=True)
    # ### end Alembic commands ###
