"""Refactor Section constraints to be per grade

Revision ID: 92af4a3cd45a
Revises: 4bdccf3f2a17
Create Date: 2026-04-30 11:55:56.843640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92af4a3cd45a'
down_revision: Union[str, Sequence[str], None] = '4bdccf3f2a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_email'), table_name='employee')
    op.create_index(op.f('ix_employee_email'), 'employee', ['email'], unique=True)
    op.create_unique_constraint('uix_grade_name_level', 'grade', ['name', 'level_id'])
    op.alter_column('school', 'ruc',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=11),
               existing_comment='Tax identification number (RUC)',
               existing_nullable=False)
    op.create_unique_constraint(None, 'school', ['ruc'])
    op.alter_column('section', 'id',
               existing_type=sa.VARCHAR(length=6),
               comment="Section code (e.g., 'SR-001', 'SE-001')",
               existing_comment="Section code (e.g., '1A', '2B')",
               existing_nullable=False)
    op.drop_constraint(op.f('section_tag_key'), 'section', type_='unique')
    op.drop_index(op.f('ix_section_name'), table_name='section')
    op.create_index(op.f('ix_section_name'), 'section', ['name'], unique=False)
    op.create_unique_constraint('uq_section_name_per_grade', 'section', ['name', 'grade_id'])
    op.create_unique_constraint('uq_section_tag_per_grade', 'section', ['tag', 'grade_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_section_tag_per_grade', 'section', type_='unique')
    op.drop_constraint('uq_section_name_per_grade', 'section', type_='unique')
    op.drop_index(op.f('ix_section_name'), table_name='section')
    op.create_index(op.f('ix_section_name'), 'section', ['name'], unique=True)
    op.create_unique_constraint(op.f('section_tag_key'), 'section', ['tag'], postgresql_nulls_not_distinct=False)
    op.alter_column('section', 'id',
               existing_type=sa.VARCHAR(length=6),
               comment="Section code (e.g., '1A', '2B')",
               existing_comment="Section code (e.g., 'SR-001', 'SE-001')",
               existing_nullable=False)
    op.drop_constraint(None, 'school', type_='unique')
    op.alter_column('school', 'ruc',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=15),
               existing_comment='Tax identification number (RUC)',
               existing_nullable=False)
    op.drop_constraint('uix_grade_name_level', 'grade', type_='unique')
    op.drop_index(op.f('ix_employee_email'), table_name='employee')
    op.create_index(op.f('ix_employee_email'), 'employee', ['email'], unique=False)
    # ### end Alembic commands ###
