"""Pequenos cambios en algunos campos

Revision ID: a27d1f90b86a
Revises: 25a10ff7cb39
Create Date: 2026-04-23 16:11:38.121600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a27d1f90b86a'
down_revision: Union[str, Sequence[str], None] = '25a10ff7cb39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    levelacademictype = postgresql.ENUM('REGULAR', 'EXTRAORDINARIA', name='levelacademictype')
    levelacademictype.create(op.get_bind(), checkfirst=True)
    
    op.add_column('level', sa.Column('type', sa.Enum('REGULAR', 'EXTRAORDINARIA', name='levelacademictype'), nullable=False, comment='Type or modality of the level'))
    op.drop_column('section', 'type')
    op.drop_column('section', 'updated_at')
    op.alter_column('student', 'gender',
               existing_type=postgresql.ENUM('MASCULINO', 'FEMENINO', name='gender'),
               nullable=False,
               existing_comment="Student's gender")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'gender',
               existing_type=postgresql.ENUM('MASCULINO', 'FEMENINO', name='gender'),
               nullable=True,
               existing_comment="Student's gender")
    op.add_column('section', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='Last update timestamp'))
    op.add_column('section', sa.Column('type', postgresql.ENUM('REGULAR', 'EXTRAORDINARIO', 'OTRO', name='sectiontype'), autoincrement=False, nullable=False, comment='Type or modality of the section'))
    op.drop_column('level', 'type')
    # ### end Alembic commands ###
