"""Initial commit

Revision ID: b90487ba53a1
Revises: 
Create Date: 2026-04-11 18:02:09.959433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b90487ba53a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_period',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Academic period ID'),
    sa.Column('name', sa.String(length=25), nullable=False, comment='Name of the academic period'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Start date of the academic period'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='End date of the academic period'),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False, comment='Active status of the academic period'),
    sa.Column('year', sa.SmallInteger(), nullable=False, comment='Year of the academic period'),
    sa.Column('type', sa.Enum('REGULAR', 'COMPLEMENTARIO', 'OTRO', name='academicperiodtype'), nullable=False, comment='Type of the academic period'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_period_id'), 'academic_period', ['id'], unique=False)
    op.create_index(op.f('ix_academic_period_name'), 'academic_period', ['name'], unique=True)
    op.create_table('employee',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False, comment='Employee ID'),
    sa.Column('first_name', sa.String(length=50), nullable=False, comment="Employee's first name"),
    sa.Column('last_name', sa.String(length=50), nullable=False, comment="Employee's last name"),
    sa.Column('dni', sa.String(length=15), nullable=False, comment='National ID document (DNI)'),
    sa.Column('ruc', sa.String(length=15), nullable=True, comment='Tax identification number (optional)'),
    sa.Column('gender', sa.Enum('MASCULINO', 'FEMENINO', name='gender'), nullable=False, comment="Employee's gender"),
    sa.Column('birth_date', sa.Date(), nullable=True, comment='Date of birth'),
    sa.Column('phone_number', sa.String(length=15), nullable=False, comment='Contact phone number'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='Contact email address'),
    sa.Column('address', sa.String(length=75), nullable=True, comment='Physical address'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Employment status flag'),
    sa.Column('position', sa.Enum('DOCENTE', 'AUXILIAR', 'SECRETARIA', 'DIRECTOR', 'SUBDIRECTOR', 'PSICOLOGO', 'PROMOTOR', 'ADMINISTRATIVO', 'OTRO', name='employeeposition'), nullable=False, comment='Current position in company'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruc')
    )
    op.create_index(op.f('ix_employee_dni'), 'employee', ['dni'], unique=True)
    op.create_index(op.f('ix_employee_email'), 'employee', ['email'], unique=False)
    op.create_index(op.f('ix_employee_id'), 'employee', ['id'], unique=False)
    op.create_table('level',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False, comment='Level ID'),
    sa.Column('name', sa.String(length=25), nullable=False, comment='Name of the educational level'),
    sa.Column('modular_code', sa.String(length=20), nullable=True, comment='Modular code for the level'),
    sa.Column('tag', sa.String(length=10), nullable=False, comment='Short tag/abbreviation for the level'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modular_code'),
    sa.UniqueConstraint('tag')
    )
    op.create_index(op.f('ix_level_id'), 'level', ['id'], unique=False)
    op.create_index(op.f('ix_level_name'), 'level', ['name'], unique=True)
    op.create_table('student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Student ID'),
    sa.Column('paternal_surname', sa.String(length=75), nullable=False, comment="Student's paternal surname"),
    sa.Column('maternal_surname', sa.String(length=75), nullable=False, comment="Student's maternal surname"),
    sa.Column('name', sa.String(length=150), nullable=False, comment="Student's first and middle name(s)"),
    sa.Column('dni', sa.String(length=12), nullable=False, comment='National ID document (DNI)'),
    sa.Column('gender', sa.Enum('MASCULINO', 'FEMENINO', name='gender'), nullable=True, comment="Student's gender"),
    sa.Column('birth_date', sa.Date(), nullable=True, comment='Date of birth'),
    sa.Column('address', sa.String(length=150), nullable=True, comment='Physical address'),
    sa.Column('phone_number', sa.String(length=15), nullable=True, comment='Contact phone number'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='Contact email address'),
    sa.Column('level', sa.String(length=25), nullable=False, comment='Educational level name'),
    sa.Column('grade', sa.String(length=25), nullable=False, comment='Grade name'),
    sa.Column('status', sa.Enum('ACTIVO', 'INACTIVO', 'RETIRADO', 'EGRESADO', name='studentstatus'), nullable=False, comment='Enrollment status of the student'),
    sa.Column('economic_level', sa.Enum('PRIMERO', 'SEGUNDO', 'TERCERO', 'CUARTO', 'QUINTO', name='economiclevel'), nullable=False, comment='Socioeconomic level classification'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Record update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_dni'), 'student', ['dni'], unique=True)
    op.create_index(op.f('ix_student_email'), 'student', ['email'], unique=False)
    op.create_index(op.f('ix_student_id'), 'student', ['id'], unique=False)
    op.create_table('grade',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False, comment='Grade ID'),
    sa.Column('name', sa.String(length=25), nullable=False, comment='Name of the academic grade'),
    sa.Column('tag', sa.String(length=10), nullable=False, comment='Short tag/abbreviation for the grade'),
    sa.Column('level_id', sa.SmallInteger(), nullable=False, comment='ID of the associated educational level'),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_index(op.f('ix_grade_id'), 'grade', ['id'], unique=False)
    op.create_index(op.f('ix_grade_level_id'), 'grade', ['level_id'], unique=False)
    op.create_index(op.f('ix_grade_name'), 'grade', ['name'], unique=True)
    op.create_table('school',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False, comment='School ID'),
    sa.Column('company_name', sa.String(length=255), nullable=False, comment='Commercial name of the school'),
    sa.Column('business_name', sa.String(length=255), nullable=False, comment='Legal business name of the institution'),
    sa.Column('management', sa.String(length=50), nullable=False, comment='Name of the management or administrative unit'),
    sa.Column('address', sa.String(length=150), nullable=False, comment='Physical address of the school'),
    sa.Column('email', sa.String(length=50), nullable=False, comment='Institutional contact email'),
    sa.Column('phone_number', sa.String(length=15), nullable=False, comment='Institutional contact phone number'),
    sa.Column('logo_path', sa.String(length=255), nullable=True, comment="File path or URL to the school's logo"),
    sa.Column('ruc', sa.String(length=15), nullable=False, comment='Tax identification number (RUC)'),
    sa.Column('dre', sa.String(length=50), nullable=True, comment='Regional Education Directorate (DRE)'),
    sa.Column('ugel', sa.String(length=50), nullable=True, comment='Local Education Management Unit (UGEL)'),
    sa.Column('headmaster_id', sa.SmallInteger(), nullable=False, comment='ID of the headmaster (Employee)'),
    sa.Column('deputy_director_id', sa.SmallInteger(), nullable=True, comment='ID of the deputy director (Employee)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['deputy_director_id'], ['employee.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['headmaster_id'], ['employee.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_id'), 'school', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False, comment='User ID'),
    sa.Column('username', sa.String(length=25), nullable=False, comment='Username of the user'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='Password of the user'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Active status of the user'),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', name='userrole'), server_default='ADMIN', nullable=False, comment='Role of the user'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp of the user'),
    sa.Column('employee_id', sa.SmallInteger(), nullable=False, comment='ID of the associated employee'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_employee_id'), 'user', ['employee_id'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('expense',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Expense ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Short description or name of the expense'),
    sa.Column('amount', sa.Numeric(precision=6, scale=2), nullable=False, comment='Expense amount'),
    sa.Column('date', sa.Date(), nullable=False, comment='Date when the expense occurred'),
    sa.Column('expense_type', sa.Enum('ADMINISTRATIVO', 'ACADEMICO', 'SERVICIOS', 'OTRO', name='expensetype'), nullable=False, comment='Type/Category of the expense'),
    sa.Column('details', sa.String(length=255), nullable=True, comment='Additional details or long description'),
    sa.Column('user_id', sa.SmallInteger(), nullable=False, comment='ID of the user who registered the expense'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_id'), 'expense', ['id'], unique=False)
    op.create_index(op.f('ix_expense_user_id'), 'expense', ['user_id'], unique=False)
    op.create_table('section',
    sa.Column('id', sa.String(length=6), nullable=False, comment="Section code (e.g., '1A', '2B')"),
    sa.Column('name', sa.String(length=25), nullable=False, comment='Name of the section'),
    sa.Column('tag', sa.String(length=10), nullable=False, comment='Short tag/abbreviation for the section'),
    sa.Column('type', sa.Enum('REGULAR', 'EXTRAORDINARIO', 'OTRO', name='sectiontype'), nullable=False, comment='Type or modality of the section'),
    sa.Column('grade_id', sa.SmallInteger(), nullable=False, comment='ID of the associated grade'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_index(op.f('ix_section_grade_id'), 'section', ['grade_id'], unique=False)
    op.create_index(op.f('ix_section_name'), 'section', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_section_name'), table_name='section')
    op.drop_index(op.f('ix_section_grade_id'), table_name='section')
    op.drop_table('section')
    op.drop_index(op.f('ix_expense_user_id'), table_name='expense')
    op.drop_index(op.f('ix_expense_id'), table_name='expense')
    op.drop_table('expense')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_employee_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_school_id'), table_name='school')
    op.drop_table('school')
    op.drop_index(op.f('ix_grade_name'), table_name='grade')
    op.drop_index(op.f('ix_grade_level_id'), table_name='grade')
    op.drop_index(op.f('ix_grade_id'), table_name='grade')
    op.drop_table('grade')
    op.drop_index(op.f('ix_student_id'), table_name='student')
    op.drop_index(op.f('ix_student_email'), table_name='student')
    op.drop_index(op.f('ix_student_dni'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_level_name'), table_name='level')
    op.drop_index(op.f('ix_level_id'), table_name='level')
    op.drop_table('level')
    op.drop_index(op.f('ix_employee_id'), table_name='employee')
    op.drop_index(op.f('ix_employee_email'), table_name='employee')
    op.drop_index(op.f('ix_employee_dni'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_academic_period_name'), table_name='academic_period')
    op.drop_index(op.f('ix_academic_period_id'), table_name='academic_period')
    op.drop_table('academic_period')
    # ### end Alembic commands ###
