"""Add user_id to charge model

Revision ID: c26af8a65e89
Revises: c507672c5e4d
Create Date: 2026-04-20 18:31:16.665463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c26af8a65e89'
down_revision: Union[str, Sequence[str], None] = 'c507672c5e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Discount ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Discount name'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Discount amount'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Flag if discount is currently active'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_id'), 'discount', ['id'], unique=False)
    op.create_table('charge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Charge ID'),
    sa.Column('charge_catalog_id', sa.Integer(), nullable=False, comment='Charge Catalog ID'),
    sa.Column('status', sa.Enum('PENDIENTE', 'PAGADO', 'VENCIDO', 'ANULADO', 'PARCIAL', name='chargestatus'), nullable=False, comment='Status of the charge'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Total initial amount'),
    sa.Column('payment_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Amount already paid'),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='Total discounted amount'),
    sa.Column('due_date', sa.Date(), nullable=False, comment='Due date'),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='Student ID'),
    sa.Column('user_id', sa.SmallInteger(), nullable=False, comment='User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['charge_catalog_id'], ['charge_catalog.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charge_charge_catalog_id'), 'charge', ['charge_catalog_id'], unique=False)
    op.create_index(op.f('ix_charge_id'), 'charge', ['id'], unique=False)
    op.create_index(op.f('ix_charge_student_id'), 'charge', ['student_id'], unique=False)
    op.create_index(op.f('ix_charge_user_id'), 'charge', ['user_id'], unique=False)
    op.create_table('charge_discount',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Charge Discount ID'),
    sa.Column('charge_id', sa.Integer(), nullable=False, comment='Charge ID'),
    sa.Column('discount_id', sa.Integer(), nullable=False, comment='Discount ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['charge_id'], ['charge.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discount_id'], ['discount.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charge_discount_charge_id'), 'charge_discount', ['charge_id'], unique=False)
    op.create_index(op.f('ix_charge_discount_discount_id'), 'charge_discount', ['discount_id'], unique=False)
    op.create_index(op.f('ix_charge_discount_id'), 'charge_discount', ['id'], unique=False)
    op.create_table('enrollment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Enrollment ID'),
    sa.Column('payment_scheme_id', sa.Integer(), nullable=False, comment='Payment Scheme ID'),
    sa.Column('academic_period_id', sa.Integer(), nullable=False, comment='Academic Period ID'),
    sa.Column('date', sa.Date(), nullable=False, comment='Date of enrollment'),
    sa.Column('section_id', sa.String(length=6), nullable=False, comment='Section ID'),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='Student ID'),
    sa.Column('user_id', sa.SmallInteger(), nullable=False, comment='User ID who registered enrollment'),
    sa.Column('status', sa.Enum('ACTIVO', 'PENDIENTE', 'RESERVADO', 'FINALIZADO', 'RETIRADO', name='enrollmentstatus'), nullable=False, comment='Status of the enrollment'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['academic_period_id'], ['academic_period.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_scheme_id'], ['payment_scheme.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollment_academic_period_id'), 'enrollment', ['academic_period_id'], unique=False)
    op.create_index(op.f('ix_enrollment_id'), 'enrollment', ['id'], unique=False)
    op.create_index(op.f('ix_enrollment_payment_scheme_id'), 'enrollment', ['payment_scheme_id'], unique=False)
    op.create_index(op.f('ix_enrollment_section_id'), 'enrollment', ['section_id'], unique=False)
    op.create_index(op.f('ix_enrollment_student_id'), 'enrollment', ['student_id'], unique=False)
    op.create_index(op.f('ix_enrollment_user_id'), 'enrollment', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrollment_user_id'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_student_id'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_section_id'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_payment_scheme_id'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_id'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_academic_period_id'), table_name='enrollment')
    op.drop_table('enrollment')
    op.drop_index(op.f('ix_charge_discount_id'), table_name='charge_discount')
    op.drop_index(op.f('ix_charge_discount_discount_id'), table_name='charge_discount')
    op.drop_index(op.f('ix_charge_discount_charge_id'), table_name='charge_discount')
    op.drop_table('charge_discount')
    op.drop_index(op.f('ix_charge_user_id'), table_name='charge')
    op.drop_index(op.f('ix_charge_student_id'), table_name='charge')
    op.drop_index(op.f('ix_charge_id'), table_name='charge')
    op.drop_index(op.f('ix_charge_charge_catalog_id'), table_name='charge')
    op.drop_table('charge')
    op.drop_index(op.f('ix_discount_id'), table_name='discount')
    op.drop_table('discount')
    # ### end Alembic commands ###
