"""Add financial and economic tracking models

Revision ID: c507672c5e4d
Revises: b90487ba53a1
Create Date: 2026-04-20 16:55:56.845660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c507672c5e4d'
down_revision: Union[str, Sequence[str], None] = 'b90487ba53a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Charge Catalog ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Charge name'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Is charge active'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charge_catalog_id'), 'charge_catalog', ['id'], unique=False)
    op.create_table('economic_level',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Economic Level ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Level name'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='Detailed description'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economic_level_id'), 'economic_level', ['id'], unique=False)
    op.create_table('guardian',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Guardian ID'),
    sa.Column('first_name', sa.String(length=50), nullable=False, comment="Guardian's first name"),
    sa.Column('last_name', sa.String(length=50), nullable=False, comment="Guardian's last name"),
    sa.Column('dni', sa.String(length=15), nullable=False, comment='National ID document (DNI)'),
    sa.Column('ruc', sa.String(length=15), nullable=True, comment='Tax identification number (optional)'),
    sa.Column('birth_date', sa.Date(), nullable=True, comment='Date of birth'),
    sa.Column('phone_number', sa.String(length=15), nullable=True, comment='Contact phone number'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='Contact email address'),
    sa.Column('address', sa.String(length=75), nullable=True, comment='Physical address'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruc')
    )
    op.create_index(op.f('ix_guardian_dni'), 'guardian', ['dni'], unique=True)
    op.create_index(op.f('ix_guardian_email'), 'guardian', ['email'], unique=False)
    op.create_index(op.f('ix_guardian_id'), 'guardian', ['id'], unique=False)
    op.create_table('payment_scheme',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Payment Scheme ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Scheme name'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_scheme_id'), 'payment_scheme', ['id'], unique=False)
    op.create_table('charge_catalog_amount',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Charge Catalog Amount ID'),
    sa.Column('charge_catalog_id', sa.Integer(), nullable=False, comment='Charge Catalog ID'),
    sa.Column('economic_level_id', sa.Integer(), nullable=True, comment='Economic Level ID'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Amount'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['charge_catalog_id'], ['charge_catalog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['economic_level_id'], ['economic_level.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charge_catalog_amount_charge_catalog_id'), 'charge_catalog_amount', ['charge_catalog_id'], unique=False)
    op.create_index(op.f('ix_charge_catalog_amount_economic_level_id'), 'charge_catalog_amount', ['economic_level_id'], unique=False)
    op.create_index(op.f('ix_charge_catalog_amount_id'), 'charge_catalog_amount', ['id'], unique=False)
    op.create_table('payment_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Payment Schedule ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Schedule name'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Start Date'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='End Date'),
    sa.Column('due_date', sa.Date(), nullable=False, comment='Due Date'),
    sa.Column('charge_catalog_id', sa.Integer(), nullable=False, comment='Charge Catalog ID'),
    sa.Column('payment_scheme_id', sa.Integer(), nullable=False, comment='Payment Scheme ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['charge_catalog_id'], ['charge_catalog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_scheme_id'], ['payment_scheme.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_schedule_charge_catalog_id'), 'payment_schedule', ['charge_catalog_id'], unique=False)
    op.create_index(op.f('ix_payment_schedule_id'), 'payment_schedule', ['id'], unique=False)
    op.create_index(op.f('ix_payment_schedule_payment_scheme_id'), 'payment_schedule', ['payment_scheme_id'], unique=False)
    op.create_table('guardian_student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Association ID'),
    sa.Column('student_id', sa.Integer(), nullable=False, comment='Student ID'),
    sa.Column('guardian_id', sa.Integer(), nullable=False, comment='Guardian ID'),
    sa.Column('relationship_type', sa.Enum('PADRE', 'MADRE', 'TIO', 'TIA', 'ABUELO', 'ABUELA', 'HERMANO', 'HERMANA', 'TUTOR', 'APODERADO', 'OTRO', name='relationshiptype'), nullable=False, comment='Type of relationship'),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardian.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardian_student_guardian_id'), 'guardian_student', ['guardian_id'], unique=False)
    op.create_index(op.f('ix_guardian_student_id'), 'guardian_student', ['id'], unique=False)
    op.create_index(op.f('ix_guardian_student_student_id'), 'guardian_student', ['student_id'], unique=False)
    op.add_column('student', sa.Column('economic_level_id', sa.Integer(), nullable=False, comment='Economic level ID'))
    op.create_index(op.f('ix_student_economic_level_id'), 'student', ['economic_level_id'], unique=False)
    op.create_foreign_key(None, 'student', 'economic_level', ['economic_level_id'], ['id'])
    op.drop_column('student', 'economic_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('economic_level', postgresql.ENUM('PRIMERO', 'SEGUNDO', 'TERCERO', 'CUARTO', 'QUINTO', name='economiclevel'), autoincrement=False, nullable=False, comment='Socioeconomic level classification'))
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_index(op.f('ix_student_economic_level_id'), table_name='student')
    op.drop_column('student', 'economic_level_id')
    op.drop_index(op.f('ix_guardian_student_student_id'), table_name='guardian_student')
    op.drop_index(op.f('ix_guardian_student_id'), table_name='guardian_student')
    op.drop_index(op.f('ix_guardian_student_guardian_id'), table_name='guardian_student')
    op.drop_table('guardian_student')
    op.drop_index(op.f('ix_payment_schedule_payment_scheme_id'), table_name='payment_schedule')
    op.drop_index(op.f('ix_payment_schedule_id'), table_name='payment_schedule')
    op.drop_index(op.f('ix_payment_schedule_charge_catalog_id'), table_name='payment_schedule')
    op.drop_table('payment_schedule')
    op.drop_index(op.f('ix_charge_catalog_amount_id'), table_name='charge_catalog_amount')
    op.drop_index(op.f('ix_charge_catalog_amount_economic_level_id'), table_name='charge_catalog_amount')
    op.drop_index(op.f('ix_charge_catalog_amount_charge_catalog_id'), table_name='charge_catalog_amount')
    op.drop_table('charge_catalog_amount')
    op.drop_index(op.f('ix_payment_scheme_id'), table_name='payment_scheme')
    op.drop_table('payment_scheme')
    op.drop_index(op.f('ix_guardian_id'), table_name='guardian')
    op.drop_index(op.f('ix_guardian_email'), table_name='guardian')
    op.drop_index(op.f('ix_guardian_dni'), table_name='guardian')
    op.drop_table('guardian')
    op.drop_index(op.f('ix_economic_level_id'), table_name='economic_level')
    op.drop_table('economic_level')
    op.drop_index(op.f('ix_charge_catalog_id'), table_name='charge_catalog')
    op.drop_table('charge_catalog')
    # ### end Alembic commands ###
