"""Modificando algunas longitud de campos, fixing

Revision ID: fedc469062e1
Revises: 107b7e531283
Create Date: 2026-05-07 00:40:19.636777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fedc469062e1'
down_revision: Union[str, Sequence[str], None] = '107b7e531283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('economic_level', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=15),
               existing_comment='Level name',
               existing_nullable=False)
    op.alter_column('economic_level', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=75),
               existing_comment='Detailed description',
               existing_nullable=True)
    op.create_unique_constraint(None, 'economic_level', ['name'])
    op.alter_column('student', 'dni',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=8),
               existing_comment='National ID document (DNI)',
               existing_nullable=False)
    op.alter_column('student', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False,
               existing_comment='Date of birth')
    op.alter_column('student', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=9),
               existing_comment='Contact phone number',
               existing_nullable=True)
    op.alter_column('student', 'level',
               existing_type=sa.VARCHAR(length=25),
               nullable=True,
               existing_comment='Educational level name')
    op.alter_column('student', 'grade',
               existing_type=sa.VARCHAR(length=25),
               nullable=True,
               existing_comment='Grade name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'grade',
               existing_type=sa.VARCHAR(length=25),
               nullable=False,
               existing_comment='Grade name')
    op.alter_column('student', 'level',
               existing_type=sa.VARCHAR(length=25),
               nullable=False,
               existing_comment='Educational level name')
    op.alter_column('student', 'phone_number',
               existing_type=sa.String(length=9),
               type_=sa.VARCHAR(length=15),
               existing_comment='Contact phone number',
               existing_nullable=True)
    op.alter_column('student', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True,
               existing_comment='Date of birth')
    op.alter_column('student', 'dni',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=12),
               existing_comment='National ID document (DNI)',
               existing_nullable=False)
    op.drop_constraint(None, 'economic_level', type_='unique')
    op.alter_column('economic_level', 'description',
               existing_type=sa.String(length=75),
               type_=sa.VARCHAR(length=255),
               existing_comment='Detailed description',
               existing_nullable=True)
    op.alter_column('economic_level', 'name',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=50),
               existing_comment='Level name',
               existing_nullable=False)
    # ### end Alembic commands ###
